# Golden Set for Utilities Knowledge Evaluation
# 30 queries testing various scenarios: version conflicts, stale-but-true nuggets, 
# ACL boundaries, freshness bias, and workflow complexity

queries:
  # Version Conflict Scenarios (newer overrides older)
  - id: "Q001"
    query: "How do I start new utility service?"
    expected_doc_ids: 
      - "UTILS:CUST:START_SERVICE:v4#overview"
      - "UTILS:CUST:START_SERVICE:v4#eligibility"
      - "UTILS:CUST:START_SERVICE:v1#eligibility"  # Still relevant for deposit info
    acl: "public"
    freshness_bias: "prefer_recent"
    category: "version_conflict"
    notes: "Should prefer v4 over v1 for general start service info"

  - id: "Q002" 
    query: "What credit score is needed to start service?"
    expected_doc_ids:
      - "UTILS:CUST:START_SERVICE:v4#eligibility"
      - "UTILS:CUST:START_SERVICE:v1#eligibility"  # Contains credit-related deposit info
    acl: "grp_care"
    freshness_bias: "prefer_recent"
    category: "version_conflict"
    notes: "v4 mentions >650 credit score, v1 focuses on deposits"

  # Stale-but-true nuggets (older docs contain accurate details)
  - id: "Q003"
    query: "Do corporate accounts need to pay deposits for new service?"
    expected_doc_ids:
      - "UTILS:CUST:START_SERVICE:v1#eligibility"
      - "UTILS:CUST:START_SERVICE:v4#eligibility"
    acl: "grp_ops" 
    freshness_bias: "accurate_over_recent"
    category: "stale_but_true"
    notes: "v1 has the nugget that corporate accounts are always exempt from deposits"

  - id: "Q004"
    query: "How are utility deposits calculated exactly?"
    expected_doc_ids:
      - "UTILS:CUST:START_SERVICE:v1#deposits"
    acl: "grp_ops"
    freshness_bias: "accurate_over_recent" 
    category: "stale_but_true"
    notes: "Detailed calculation methodology only in v1, still used by billing systems"

  - id: "Q005"
    query: "What are the specific reconnection fees and surcharges?"
    expected_doc_ids:
      - "UTILS:CUST:RECONNECT:v1#fees"
      - "UTILS:CUST:RECONNECT:v2#process"
    acl: "grp_ops"
    freshness_bias: "accurate_over_recent"
    category: "stale_but_true" 
    notes: "v1 has detailed fee structure still used by billing systems"

  - id: "Q006"
    query: "Are there special payment plan benefits for medical emergencies?"
    expected_doc_ids:
      - "UTILS:BILLING:PAYMENT_PLAN:v1#hardship"
      - "UTILS:BILLING:PAYMENT_PLAN:v2#eligibility"  # General eligibility context
      - "UTILS:BILLING:PAYMENT_PLAN:v2#overview"  # Payment plan overview
    acl: "grp_care"
    freshness_bias: "accurate_over_recent"
    category: "stale_but_true"
    notes: "Medical hardship details only documented in v1 but still valid"

  - id: "Q007" 
    query: "What safety equipment specifications are required for field work?"
    expected_doc_ids:
      - "UTILS:FIELD:SAFETY:v1#equipment"
      - "UTILS:FIELD:SAFETY:v2#procedures"
    acl: "grp_ops"
    freshness_bias: "accurate_over_recent"
    category: "stale_but_true"
    notes: "Specific equipment specs in v1 are still current standards"

  # Workflow scenarios (multi-step processes)
  - id: "Q008"
    query: "Walk me through stopping utility service"
    expected_doc_ids:
      - "UTILS:CUST:STOP_SERVICE:v3#overview"
      - "UTILS:CUST:STOP_SERVICE:v3#final_bill"
    acl: "public"
    freshness_bias: "prefer_recent"
    category: "workflow"
    notes: "Complete stop service workflow"

  - id: "Q009"
    query: "How do I set up a payment plan for past due bills?"
    expected_doc_ids:
      - "UTILS:BILLING:PAYMENT_PLAN:v2#overview"
      - "UTILS:BILLING:PAYMENT_PLAN:v2#eligibility"
    acl: "grp_care"
    freshness_bias: "prefer_recent"
    category: "workflow"
    notes: "Payment plan setup process"

  - id: "Q010"
    query: "What's the process for correcting a wrong meter reading?"
    expected_doc_ids:
      - "UTILS:METER:READ_CORRECTION:v2#process"
      - "UTILS:METER:READ_CORRECTION:v2#thresholds"
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "workflow"
    notes: "Meter correction workflow with thresholds"

  - id: "Q011"
    query: "How do I switch to time-of-use rates?"
    expected_doc_ids:
      - "UTILS:RATE:TOU_SWITCH:v3#overview"
      - "UTILS:RATE:TOU_SWITCH:v3#eligibility"
    acl: "public"
    freshness_bias: "prefer_recent"
    category: "workflow"
    notes: "TOU rate switching process"

  - id: "Q012"
    query: "How do I reconnect service after disconnection?"
    expected_doc_ids:
      - "UTILS:CUST:RECONNECT:v2#process"
      - "UTILS:CUST:RECONNECT:v1#fees"  # Fee information is relevant
    acl: "grp_care"
    freshness_bias: "prefer_recent"
    category: "workflow"
    notes: "Service reconnection workflow"

  - id: "Q013"
    query: "What's the bill dispute process?"
    expected_doc_ids:
      - "UTILS:BILLING:DISPUTE:v3#overview"
      - "UTILS:BILLING:DISPUTE:v2#investigation"
    acl: "grp_care"
    freshness_bias: "prefer_recent"
    category: "workflow"
    notes: "Bill dispute workflow, may need both versions"

  # API/Technical Documentation
  - id: "Q014"
    query: "Show me the Customer Summary API"
    expected_doc_ids:
      - "UTILS:API:CUSTOMER_SUMMARY:v2"
      - "UTILS:API:ACCOUNT_UTILITY:v3"  # Related account API
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "api"
    notes: "API documentation lookup"

  - id: "Q015"
    query: "How do I search transaction history via API?"
    expected_doc_ids:
      - "UTILS:API:ENHANCED_TRANSACTION:v1"
      - "UTILS:API:CUSTOMER_SUMMARY:v2"  # May include transaction info
      - "UTILS:API:ACCOUNT_UTILITY:v3"  # Account-related transactions
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "api"
    notes: "Transaction search API"

  - id: "Q016"
    query: "What APIs are available for account information?"
    expected_doc_ids:
      - "UTILS:API:ACCOUNT_UTILITY:v3"
      - "UTILS:API:CUSTOMER_SUMMARY:v2"
      - "UTILS:API:ENHANCED_TRANSACTION:v1"  # Transaction history is account info
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "api"
    notes: "Account-related APIs"

  - id: "Q017"
    query: "How do I log customer interactions via API?"
    expected_doc_ids:
      - "UTILS:API:CUSTOMER_INTERACTION:v2"
    acl: "grp_care"
    freshness_bias: "prefer_recent"
    category: "api"
    notes: "Customer interaction API"

  - id: "Q018"
    query: "What digital events can I track?"
    expected_doc_ids:
      - "UTILS:API:DIGITAL_EVENTS:v1"
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "api"
    notes: "Digital events API"

  # Platform and System queries
  - id: "Q019"
    query: "Tell me about the Global Customer Platform"
    expected_doc_ids:
      - "UTILS:GLOBAL:PLATFORM:v2"
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "platform"
    notes: "Platform overview"

  - id: "Q020"
    query: "What products are in the utility catalog?"
    expected_doc_ids:
      - "UTILS:API:PRODUCT_CATALOG:v1"
    acl: "public"
    freshness_bias: "prefer_recent"
    category: "platform"
    notes: "Product catalog information"

  # Emergency and Operations
  - id: "Q021"
    query: "How do I report a power outage?"
    expected_doc_ids:
      - "UTILS:EMERGENCY:OUTAGE:v1#reporting"
      - "UTILS:EMERGENCY:OUTAGE:v1#restoration"  # Related outage information
    acl: "public"
    freshness_bias: "prefer_recent"
    category: "emergency"
    notes: "Outage reporting process"

  - id: "Q022"
    query: "What's the priority order for power restoration?"
    expected_doc_ids:
      - "UTILS:EMERGENCY:OUTAGE:v1#restoration"
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "emergency"
    notes: "Restoration priorities"

  - id: "Q023"
    query: "What are the field safety requirements?"
    expected_doc_ids:
      - "UTILS:FIELD:SAFETY:v2#procedures"
      - "UTILS:FIELD:SAFETY:v1#equipment"
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "safety"
    notes: "Safety procedures and equipment"

  # Regulatory and Rates
  - id: "Q024"
    query: "What are the current residential electricity rates?"
    expected_doc_ids:
      - "UTILS:REGULATORY:TARIFF:v4#residential"
      - "UTILS:RATE:TOU_SWITCH:v3#overview"  # Time-of-use rates are residential
      - "UTILS:RATE:TOU_SWITCH:v3#eligibility"  # TOU eligibility info
    acl: "public"
    freshness_bias: "prefer_recent"
    category: "regulatory"
    notes: "Current residential rates"

  - id: "Q025"
    query: "Show me commercial rate structure"
    expected_doc_ids:
      - "UTILS:REGULATORY:TARIFF:v3#commercial"
      - "UTILS:RATE:TOU_SWITCH:v3#overview"  # May include commercial TOU info
    acl: "public"
    freshness_bias: "prefer_recent"
    category: "regulatory"
    notes: "Commercial rates and tiers"

  # Training and HR
  - id: "Q026"
    query: "What's the new employee onboarding process?"
    expected_doc_ids:
      - "UTILS:TRAINING:ONBOARD:v2#overview"
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "training"
    notes: "Onboarding program"

  - id: "Q027"
    query: "What certifications do field technicians need?"
    expected_doc_ids:
      - "UTILS:TRAINING:CERT:v1#requirements"
    acl: "grp_ops"
    freshness_bias: "prefer_recent"
    category: "training"
    notes: "Certification requirements by role"

  # ACL boundary tests
  - id: "Q028"
    query: "payment plan eligibility requirements"
    expected_doc_ids:
      - "UTILS:BILLING:PAYMENT_PLAN:v2#eligibility"
      - "UTILS:BILLING:PAYMENT_PLAN:v2#overview"  # General overview is relevant
    acl: "public"  # Should NOT find grp_care restricted docs
    freshness_bias: "prefer_recent"
    category: "acl_boundary"
    notes: "Public user should not see care-restricted eligibility details"

  - id: "Q029"
    query: "start service eligibility with credit requirements"
    expected_doc_ids: []  # Should find nothing - ACL mismatch
    acl: "public"  # grp_care doc should not be returned
    freshness_bias: "prefer_recent"
    category: "acl_boundary"
    notes: "Public user should not access care team eligibility doc"

  # Complex multi-aspect queries
  - id: "Q030"
    query: "service reconnection process including all fees and requirements"
    expected_doc_ids:
      - "UTILS:CUST:RECONNECT:v2#process"
      - "UTILS:CUST:RECONNECT:v1#fees"
    acl: "grp_ops"
    freshness_bias: "comprehensive"
    category: "comprehensive"
    notes: "Needs both recent process and detailed fee structure from older doc"

# Evaluation Metrics Configuration
evaluation:
  metrics:
    - "recall@10"
    - "ndcg@10"
    - "precision@5"
  thresholds:
    recall@10_min: 0.8
    ndcg@10_min: 0.7
    precision@5_min: 0.6
  
# Test Configuration
test_config:
  index_name: "confluence_mock"
  batch_size: 5
  timeout_seconds: 30
  verbose: true